version: 2.1
jobs:
  compile:
   docker:
      - image: panchajanya1999/archlinux:latest
   resource_class: large
   steps:
      - run:
          command: |
           git config --global user.name "venom-stark"
           git config --global user.email "sachidanandabehera562@gmail.com"
           git clone --depth=1 https://venom-stark:$GITHUB_TOKEN@github.com/venom-stark/kernel_xiaomi_mojito-test -b ${CIRCLE_BRANCH} .
           bash .circleci/kramel.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
